"""
Image retrieval helper module for ECEasy backend.

Loads the image manifest generated by ingest_FAISS.py and provides
utilities to search for and retrieve image metadata that relates to queries.

Example usage:
    from image_retrieval import ImageRetriever
    
    retriever = ImageRetriever()
    
    # Search images by course code
    images = retriever.search_by_course_code("ELEC1100")
    
    # Search images by department
    images = retriever.search_by_department("ELEC")
    
    # Search images by keywords from filename/description
    images = retriever.search_by_keywords(["study", "pattern"])
    
    # Get all images of a specific doc type
    images = retriever.search_by_doc_type("course_requirement")
"""

import json
from pathlib import Path
from typing import List, Optional, Dict, Any
import re
from loguru import logger


COURSE_CODE_RE = re.compile(r"\b([A-Za-z]{4})\s*[-_]?\s*(\d{4}[A-Za-z]?)\b", re.IGNORECASE)
TOKEN_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_\-+&]{1,}")
STOPWORDS = {
    "the", "a", "an", "and", "or", "to", "of", "for", "in", "on", "at", "with", "is", "are",
    "what", "how", "why", "can", "could", "should", "would", "need", "about", "show", "tell",
    "please", "question", "questions", "course", "courses", "student", "students",
}
VISUAL_INTENT_TERMS = {
    "image", "images", "diagram", "chart", "flow", "table", "pathway", "pattern", "study",
    "curriculum", "structure", "track", "group", "map", "plan",
}


def _normalize_course_code(raw: str) -> str:
    compact = re.sub(r"\s+", "", raw).replace("-", "").replace("_", "").upper()
    m = COURSE_CODE_RE.search(compact)
    if not m:
        return ""
    return f"{m.group(1).upper()}{m.group(2).upper()}"


def _extract_course_codes(text: str) -> List[str]:
    found = {_normalize_course_code(m.group(0)) for m in COURSE_CODE_RE.finditer(text or "")}
    return [code for code in sorted(found) if code]


def _tokenize(text: str) -> List[str]:
    tokens = []
    for t in TOKEN_RE.findall((text or "").lower()):
        if len(t) < 3 and not any(ch.isdigit() for ch in t):
            continue
        if t in STOPWORDS:
            continue
        tokens.append(t)
    return tokens


def _has_visual_intent(text: str) -> bool:
    tokens = set(_tokenize(text))
    return bool(tokens & VISUAL_INTENT_TERMS)


def _dedupe_by_relpath(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    seen = set()
    deduped = []
    for img in items:
        relpath = img.get("source_relpath", "")
        if relpath in seen:
            continue
        seen.add(relpath)
        deduped.append(img)
    return deduped


def _suggestion_debug_line(mode: str, query: str, query_codes: List[str], selected: List[Dict[str, Any]]) -> str:
    preview_paths = [img.get("source_relpath", "") for img in selected[:5]]
    return (
        f"[ImageSuggest] mode={mode} codes={query_codes or []} count={len(selected)} "
        f"query='{query[:120]}' paths={preview_paths}"
    )


class ImageRetriever:
    """Load and query image manifests from FAISS index directories."""

    def __init__(self, faiss_index_path: Optional[str] = None, embedding_model: Optional[str] = None):
        """
        Initialize image retriever.
        
        Args:
            faiss_index_path: Direct path to FAISS index (optional).
                If not provided, will auto-derive from EMBEDDING_MODEL_HUB_NAME in .env
            embedding_model: Name of embedding model (for deriving index path).
                If not provided, defaults to "all-MiniLM-L6-v2"
        """
        self.manifest_data: List[Dict[str, Any]] = []
        self.manifest_path: Optional[Path] = None

        if faiss_index_path:
            self.manifest_path = Path(faiss_index_path) / "image_manifest.json"
        else:
            # Auto-derive from embedding model name (same logic as ingest_FAISS.py)
            import os
            from dotenv import load_dotenv
            load_dotenv(override=True)
            
            model_name = embedding_model or os.environ.get("EMBEDDING_MODEL_HUB_NAME", "all-MiniLM-L6-v2").strip()
            short_name = model_name.split("/")[-1]
            index_path = f"faiss_index_{short_name}"
            self.manifest_path = Path(index_path) / "image_manifest.json"

        self._load_manifest()

    def _load_manifest(self) -> None:
        """Load and parse image manifest JSON."""
        if not self.manifest_path or not self.manifest_path.exists():
            logger.warning(f"Image manifest not found at {self.manifest_path}. No images available.")
            self.manifest_data = []
            return

        try:
            with open(self.manifest_path, "r", encoding="utf-8") as f:
                self.manifest_data = json.load(f)
            logger.info(f"Loaded {len(self.manifest_data)} images from manifest")
        except Exception as e:
            logger.error(f"Failed to load image manifest: {e}")
            self.manifest_data = []

    def search_by_course_code(self, course_code: str) -> List[Dict[str, Any]]:
        """
        Search for images related to a specific course code.
        
        Args:
            course_code: Course code (e.g., "ELEC1100", "comp2011")
        
        Returns:
            List of image metadata dicts matching the course code.
        """
        normalized = _normalize_course_code(course_code)
        if not normalized:
            return []
        return [img for img in self.manifest_data if img.get("course_code", "").upper() == normalized]

    def search_by_department(self, dept: str) -> List[Dict[str, Any]]:
        """
        Search for images from a specific department.
        
        Args:
            dept: Department code (e.g., "ELEC", "COMP")
        
        Returns:
            List of image metadata dicts from the department.
        """
        normalized = dept.upper()
        return [img for img in self.manifest_data if img.get("department", "").upper() == normalized]

    def search_by_doc_type(self, doc_type: str) -> List[Dict[str, Any]]:
        """
        Search for images by document type.
        
        Args:
            doc_type: Document type (e.g., "course_syllabus", "course_requirement", "general")
        
        Returns:
            List of image metadata dicts of the given type.
        """
        return [img for img in self.manifest_data if img.get("doc_type", "") == doc_type]

    def search_by_keywords(self, keywords: List[str], field: str = "description") -> List[Dict[str, Any]]:
        """
        Search for images by keywords in a specific field (e.g., description, filename).
        
        Args:
            keywords: List of keywords to search for
            field: Metadata field to search ("description", "source_name", "source_relpath")
        
        Returns:
            List of image metadata dicts containing any of the keywords.
        """
        cleaned_keywords = [k.lower().strip() for k in keywords if len(k.strip()) >= 3 and k.lower().strip() not in STOPWORDS]
        if not cleaned_keywords:
            return []

        results = []
        for img in self.manifest_data:
            text = img.get(field, "").lower()
            if any(kw in text for kw in cleaned_keywords):
                results.append(img)
        return results

    def search_by_query(self, query: str) -> List[Dict[str, Any]]:
        """
        Fuzzy search images by query string.
        Searches across course code, department, and description.
        
        Args:
            query: Search query (e.g., "ELEC study pattern", "common core")
        
        Returns:
            List of image metadata dicts matching the query.
        """
        results = []
        query_tokens = _tokenize(query)
        query_codes = set(_extract_course_codes(query))

        for img in self.manifest_data:
            score = 0.0
            matched_terms = 0

            course_code = str(img.get("course_code", "")).upper()
            department = str(img.get("department", "")).lower()
            description = str(img.get("description", "")).lower()
            source_name = str(img.get("source_name", "")).lower()
            source_relpath = str(img.get("source_relpath", "")).lower()
            doc_type = str(img.get("doc_type", "")).lower()

            if query_codes:
                if course_code in query_codes:
                    score += 100.0
                else:
                    # If query has an explicit course code, do not surface unrelated course-track images.
                    continue

            for token in query_tokens:
                token_hit = False
                if token in description:
                    score += 3.0
                    token_hit = True
                if token in source_name:
                    score += 2.0
                    token_hit = True
                if token in source_relpath:
                    score += 2.0
                    token_hit = True
                if token in doc_type:
                    score += 1.0
                    token_hit = True
                if token == department:
                    score += 4.0
                    token_hit = True
                if token_hit:
                    matched_terms += 1

            if query_codes and score >= 100.0:
                enriched = dict(img)
                enriched["_relevance_score"] = round(score, 3)
                results.append(enriched)
                continue

            if (not query_codes) and score >= 4.0 and matched_terms >= 1:
                enriched = dict(img)
                enriched["_relevance_score"] = round(score, 3)
                results.append(enriched)

        results.sort(key=lambda x: x.get("_relevance_score", 0), reverse=True)
        return results

    def get_all_images(self) -> List[Dict[str, Any]]:
        """Get all cataloged images."""
        return self.manifest_data

    def get_image_by_relpath(self, relpath: str) -> Optional[Dict[str, Any]]:
        """
        Get a single image by its relative path.
        
        Args:
            relpath: Relative path (e.g., "course syllabus/ELEC/ELEC1100.png")
        
        Returns:
            Image metadata dict, or None if not found.
        """
        normalized = relpath.replace("\\", "/").lower()
        for img in self.manifest_data:
            if img.get("source_relpath", "").lower() == normalized:
                return img
        return None

    def get_image_path(self, img_metadata: Dict[str, Any]) -> Path:
        """
        Get the full filesystem path to an image.
        
        Args:
            img_metadata: Image metadata dict from search results
        
        Returns:
            Full Path object to the image file.
        """
        relpath = img_metadata.get("source_relpath", "")
        return Path("ECEknowledge") / relpath


def suggest_images_for_response(query: str, response_text: str, retriever: Optional[ImageRetriever] = None) -> List[Dict[str, Any]]:
    """
    Suggest relevant images for a chatbot response based on query and response content.
    
    Args:
        query: User's original query
        response_text: Bot's response text
        retriever: ImageRetriever instance (creates new one if not provided)
    
    Returns:
        List of suggested image metadata dicts.
    """
    if retriever is None:
        retriever = ImageRetriever()

    if not retriever.manifest_data:
        return []

    query_codes = _extract_course_codes(query)

    # Priority 1: strict exact course-code mapping from user query only.
    if query_codes:
        suggested = []
        for code in query_codes:
            suggested.extend(retriever.search_by_course_code(code))
        selected = _dedupe_by_relpath(suggested)[:5]
        logger.info(_suggestion_debug_line("strict_course_code", query, query_codes, selected))
        return selected

    # Priority 2: only run fuzzy retrieval when query has no explicit course code.
    ranked = retriever.search_by_query(query)
    if ranked:
        selected = _dedupe_by_relpath(ranked)[:5]
        logger.info(_suggestion_debug_line("fuzzy_ranked", query, query_codes, selected))
        return selected

    # Priority 3: optional low-confidence fallback only for explicit visual intent.
    if _has_visual_intent(query):
        keywords = _tokenize(query)
        if response_text:
            keywords.extend(_tokenize(response_text)[:6])
        fallback = retriever.search_by_keywords(keywords, field="description")
        fallback.extend(retriever.search_by_keywords(keywords, field="source_name"))
        selected = _dedupe_by_relpath(fallback)[:5]
        logger.info(_suggestion_debug_line("visual_fallback", query, query_codes, selected))
        return selected

    logger.info(_suggestion_debug_line("no_match", query, query_codes, []))
    return []


if __name__ == "__main__":
    # Quick test
    retriever = ImageRetriever()
    
    print(f"Total images in manifest: {len(retriever.get_all_images())}")
    
    # Test search functions
    elec_images = retriever.search_by_department("ELEC")
    print(f"ELEC department images: {len(elec_images)}")
    for img in elec_images:
        print(f"  - {img['source_relpath']}: {img['description']}")
    
    # Test query search
    results = retriever.search_by_query("ELEC curriculum")
    print(f"\nSearch results for 'ELEC curriculum': {len(results)}")
    for img in results:
        print(f"  - {img['source_relpath']} (score: {img.get('_relevance_score', 0)})")

