"""
Image retrieval helper module for ECEasy backend.

Loads the image manifest generated by ingest_FAISS.py and provides
utilities to search for and retrieve image metadata that relates to queries.

Example usage:
    from image_retrieval import ImageRetriever
    
    retriever = ImageRetriever()
    
    # Search images by course code
    images = retriever.search_by_course_code("ELEC1100")
    
    # Search images by department
    images = retriever.search_by_department("ELEC")
    
    # Search images by keywords from filename/description
    images = retriever.search_by_keywords(["study", "pattern"])
    
    # Get all images of a specific doc type
    images = retriever.search_by_doc_type("course_requirement")
"""

import json
from pathlib import Path
from typing import List, Optional, Dict, Any
import re
from loguru import logger


class ImageRetriever:
    """Load and query image manifests from FAISS index directories."""

    def __init__(self, faiss_index_path: Optional[str] = None, embedding_model: Optional[str] = None):
        """
        Initialize image retriever.
        
        Args:
            faiss_index_path: Direct path to FAISS index (optional).
                If not provided, will auto-derive from EMBEDDING_MODEL_HUB_NAME in .env
            embedding_model: Name of embedding model (for deriving index path).
                If not provided, defaults to "all-MiniLM-L6-v2"
        """
        self.manifest_data: List[Dict[str, Any]] = []
        self.manifest_path: Optional[Path] = None

        if faiss_index_path:
            self.manifest_path = Path(faiss_index_path) / "image_manifest.json"
        else:
            # Auto-derive from embedding model name (same logic as ingest_FAISS.py)
            import os
            from dotenv import load_dotenv
            load_dotenv(override=True)
            
            model_name = embedding_model or os.environ.get("EMBEDDING_MODEL_HUB_NAME", "all-MiniLM-L6-v2").strip()
            short_name = model_name.split("/")[-1]
            index_path = f"faiss_index_{short_name}"
            self.manifest_path = Path(index_path) / "image_manifest.json"

        self._load_manifest()

    def _load_manifest(self) -> None:
        """Load and parse image manifest JSON."""
        if not self.manifest_path or not self.manifest_path.exists():
            logger.warning(f"Image manifest not found at {self.manifest_path}. No images available.")
            self.manifest_data = []
            return

        try:
            with open(self.manifest_path, "r", encoding="utf-8") as f:
                self.manifest_data = json.load(f)
            logger.info(f"Loaded {len(self.manifest_data)} images from manifest")
        except Exception as e:
            logger.error(f"Failed to load image manifest: {e}")
            self.manifest_data = []

    def search_by_course_code(self, course_code: str) -> List[Dict[str, Any]]:
        """
        Search for images related to a specific course code.
        
        Args:
            course_code: Course code (e.g., "ELEC1100", "comp2011")
        
        Returns:
            List of image metadata dicts matching the course code.
        """
        normalized = course_code.upper().replace(" ", "").replace("-", "")
        return [img for img in self.manifest_data if img.get("course_code", "").upper() == normalized]

    def search_by_department(self, dept: str) -> List[Dict[str, Any]]:
        """
        Search for images from a specific department.
        
        Args:
            dept: Department code (e.g., "ELEC", "COMP")
        
        Returns:
            List of image metadata dicts from the department.
        """
        normalized = dept.upper()
        return [img for img in self.manifest_data if img.get("department", "").upper() == normalized]

    def search_by_doc_type(self, doc_type: str) -> List[Dict[str, Any]]:
        """
        Search for images by document type.
        
        Args:
            doc_type: Document type (e.g., "course_syllabus", "course_requirement", "general")
        
        Returns:
            List of image metadata dicts of the given type.
        """
        return [img for img in self.manifest_data if img.get("doc_type", "") == doc_type]

    def search_by_keywords(self, keywords: List[str], field: str = "description") -> List[Dict[str, Any]]:
        """
        Search for images by keywords in a specific field (e.g., description, filename).
        
        Args:
            keywords: List of keywords to search for
            field: Metadata field to search ("description", "source_name", "source_relpath")
        
        Returns:
            List of image metadata dicts containing any of the keywords.
        """
        results = []
        for img in self.manifest_data:
            text = img.get(field, "").lower()
            if any(kw.lower() in text for kw in keywords):
                results.append(img)
        return results

    def search_by_query(self, query: str) -> List[Dict[str, Any]]:
        """
        Fuzzy search images by query string.
        Searches across course code, department, and description.
        
        Args:
            query: Search query (e.g., "ELEC study pattern", "common core")
        
        Returns:
            List of image metadata dicts matching the query.
        """
        results = []
        query_lower = query.lower()
        
        for img in self.manifest_data:
            # Score based on matches across different fields
            score = 0
            if query_lower in img.get("course_code", "").lower():
                score += 10
            if query_lower in img.get("department", "").lower():
                score += 5
            if query_lower in img.get("description", "").lower():
                score += 3
            if query_lower in img.get("source_name", "").lower():
                score += 2
            if query_lower in img.get("doc_type", "").lower():
                score += 1
            
            if score > 0:
                img["_relevance_score"] = score
                results.append(img)
        
        # Sort by relevance score
        results.sort(key=lambda x: x.get("_relevance_score", 0), reverse=True)
        return results

    def get_all_images(self) -> List[Dict[str, Any]]:
        """Get all cataloged images."""
        return self.manifest_data

    def get_image_by_relpath(self, relpath: str) -> Optional[Dict[str, Any]]:
        """
        Get a single image by its relative path.
        
        Args:
            relpath: Relative path (e.g., "course syllabus/ELEC/ELEC1100.png")
        
        Returns:
            Image metadata dict, or None if not found.
        """
        normalized = relpath.replace("\\", "/").lower()
        for img in self.manifest_data:
            if img.get("source_relpath", "").lower() == normalized:
                return img
        return None

    def get_image_path(self, img_metadata: Dict[str, Any]) -> Path:
        """
        Get the full filesystem path to an image.
        
        Args:
            img_metadata: Image metadata dict from search results
        
        Returns:
            Full Path object to the image file.
        """
        relpath = img_metadata.get("source_relpath", "")
        return Path("ECEknowledge") / relpath


def suggest_images_for_response(query: str, response_text: str, retriever: Optional[ImageRetriever] = None) -> List[Dict[str, Any]]:
    """
    Suggest relevant images for a chatbot response based on query and response content.
    
    Args:
        query: User's original query
        response_text: Bot's response text
        retriever: ImageRetriever instance (creates new one if not provided)
    
    Returns:
        List of suggested image metadata dicts.
    """
    if retriever is None:
        retriever = ImageRetriever()

    if not retriever.manifest_data:
        return []

    # Extract course codes from query and response
    course_code_pattern = re.compile(r"[A-Za-z]{4}\s*\d{4}[A-Za-z]?", re.IGNORECASE)
    codes_in_query = course_code_pattern.findall(query)
    codes_in_response = course_code_pattern.findall(response_text)

    all_codes = set(codes_in_query + codes_in_response)

    suggested = []

    # Search by course code
    for code in all_codes:
        images = retriever.search_by_course_code(code)
        suggested.extend(images)

    # Fallback: search by keywords from query
    if not suggested:
        keywords = query.lower().split()
        suggested = retriever.search_by_keywords(keywords)

    # Remove duplicates by source_relpath
    seen = set()
    unique_suggestions = []
    for img in suggested:
        relpath = img.get("source_relpath", "")
        if relpath not in seen:
            seen.add(relpath)
            unique_suggestions.append(img)

    return unique_suggestions[:5]  # Return top 5 suggestions


if __name__ == "__main__":
    # Quick test
    retriever = ImageRetriever()
    
    print(f"Total images in manifest: {len(retriever.get_all_images())}")
    
    # Test search functions
    elec_images = retriever.search_by_department("ELEC")
    print(f"ELEC department images: {len(elec_images)}")
    for img in elec_images:
        print(f"  - {img['source_relpath']}: {img['description']}")
    
    # Test query search
    results = retriever.search_by_query("ELEC curriculum")
    print(f"\nSearch results for 'ELEC curriculum': {len(results)}")
    for img in results:
        print(f"  - {img['source_relpath']} (score: {img.get('_relevance_score', 0)})")

